In [12]:
print("starting my new learning journey for genai ds")


starting my new learning journey for genai ds


In [13]:
import numpy as np


In [14]:
l=[1,2,3,4]
print(l)


[1, 2, 3, 4]


In [15]:
narray=np.array(l)
print(narray)
print(type(narray))


[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
#np arrays are homogeneous can be accessed only on one data type at once unlike lists which is heterogeneous

a=["asadds",1,3.98,True]
print(a,type(a))


['asadds', 1, 3.98, True] <class 'list'>


In [17]:
b=np.array(a)

print(b,type(b))


['asadds' '1' '3.98' 'True'] <class 'numpy.ndarray'>


In [18]:
print(b.ndim)


1


In [19]:
b


array(['asadds', '1', '3.98', 'True'], dtype='<U32')

In [21]:
c= np.arange(1,10)
c


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
c=np.arange(1,10,2)
c


array([1, 3, 5, 7, 9])

In [27]:
c=np.arange(1,10,.5)
c


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])