In [1]:
print("starting my new learning journey for genai ds")


starting my new learning journey for genai ds


In [2]:
import numpy as np


In [3]:
l=[1,2,3,4]
print(l)


[1, 2, 3, 4]


In [4]:
narray=np.array(l)
print(narray)
print(type(narray))


[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
#np arrays are homogeneous can be accessed only on one data type at once unlike lists which is heterogeneous

a=["asadds",1,3.98,True]
print(a,type(a))


['asadds', 1, 3.98, True] <class 'list'>


In [6]:
b=np.array(a)

print(b,type(b))


['asadds' '1' '3.98' 'True'] <class 'numpy.ndarray'>


In [7]:
print(b.ndim)


1


In [8]:
b


array(['asadds', '1', '3.98', 'True'], dtype='<U32')

In [9]:
c= np.arange(1,10)
c


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c=np.arange(1,10,2)
c


array([1, 3, 5, 7, 9])

In [11]:
c=np.arange(1,10,.5)
c


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [12]:
d=np.array([1,2,3,4],dtype="str")
d


array(['1', '2', '3', '4'], dtype='<U1')

In [14]:
d=np.array(['a','c',3,4],dtype="integer")
d


TypeError: data type 'integer' not understood

In [15]:
d=np.array([1,2,3,4])
type(d)


numpy.ndarray

In [16]:
d.dtype


dtype('int64')

In [17]:
d=np.array(['a','c',3,4],dtype="int64")
d


ValueError: invalid literal for int() with base 10: 'a'

In [19]:
d=np.array(['a','c',3,4],dtype="str")
d


array(['a', 'c', '3', '4'], dtype='<U1')

In [20]:
d=np.array(['a','c',3,4],dtype="float")
d


ValueError: could not convert string to float: 'a'

In [21]:
d=np.array(['a','c',3,4],dtype="integer")
d


TypeError: data type 'integer' not understood

In [22]:
d=np.array(['a','c',3,4],dtype="int")
d


ValueError: invalid literal for int() with base 10: 'a'

In [23]:
for i in range(1,100,-1):
print(i)


IndentationError: expected an indented block after 'for' statement on line 1 (2103154855.py, line 2)

In [25]:
for i in range(1,100,1):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [27]:
for i in range(1,100,-1):  #will not give output as it is not applicable ie negative indexing cannot be applied on a positive range of 1 to 100
    print(i)


In [28]:
np.arange(100)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
np.arange(1,100)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
np.arange(1,100,3)  #with step size of 3


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [32]:
np.arange(1,100,3).ndim  #with step size of 3


1

In [33]:
np.arange(1,100,3).shape  #shape gives you number of elements here as it is 1d


(33,)

In [35]:
# Given an array of marks, return the array only containing elements with marks > 40
# Input Format:

# A 1D numpy array
# Output Format:

# A 1D numpy array
# Sample Input:

# [85, 18, 2, 57, 65, 44]
# Sample Output:

# [85, 57, 65, 44]

arr=np.array([85, 18, 2, 57, 65, 44])
mask=arr>40

arr[mask]


array([85, 57, 65, 44])

In [36]:
# import numpy as np
# x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
# x[(x >= -5) & (x <= 15)] *= -1
# print(x) 

#output willbe  [-5,9,5,10,-8]

import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

#need to check this output/analyze


[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
# Given a NumPy array of integer elements, write a program that calculates the sigmoid value of each of those elements and returns these sigmoid values rounded up to 2 decimal places in a NumPy array.

# The value of sigmoid function for an element x is:

# Sigmoid(x) =  
# (1+e 
# −x
#  )
# 1
# ​
 

# Input Format:

# A list of integers is taken as input which is then typecasted to NumPy array and passed as an argument.
# Output Format:

# A NumPy array with float values rounded off to two decimal places.
# Sample Input:

# [-2, -1, 0, 1, 2]
# Sample Output:

# [0.12 0.27 0.5 0.73 0.88]


In [ ]:
# 

ToDO
