In [13]:
# 1.)
# Problem Statement:

# Given the row count of a square array and an integer number k,

# return a 2D square array where

# all diagonal elements are k and
# all non-diagonal elements are 0.
# Note: The returned 2D array should be of integer type.

# Input Format:

# Input has two lines.
# First line corresponds to the row count.
# Second line is the integer k.
# Output Format:

# A 2D square array
# Sample Input:

# 3
# 300
# Sample Output:

# [[300, 0, 0],
#  [0, 300, 0]
#  [0, 0, 300]]
# Note: We can use special arrays to solve this.

import numpy as np
cols=rows=3
k=300

a=np.zeros((cols,rows),dtype='int')


In [14]:
a


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
b=None
np.fill_diagonal(a,k)
print(np.fill_diagonal(a,k))


None


In [20]:
b


In [ ]:
array = np.zeros((rows,cols), dtype=int)
array =    np.fill_diagonal(array, k)  #not working


In [30]:
np.eye(rows,dtype='int')*k


array([[300,   0,   0],
       [  0, 300,   0],
       [  0,   0, 300]])

In [38]:
#What will be the outcome of the following code snippet ?

d = np.ones((5,5))
d
d[1:-1,1:-1] 
# d


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# Given a array of bird names and another array with corresponding ages of the birds, find the name of the oldest bird in the list.

# Input Format:

# Input has two lines.
# First line is the array of bird names (String).
# Second line is the array of ages of the birds (Int).
# Output Format:

# string
# Sample Input:

# ['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  
# [6, 1, 6, 5, 7, 6, 0, 9, 0, 7]
# Sample Output:

# parrot
# Explanation:

# parrot has age 9 which is the max of all the ages in the array; therefore parrot is returned.
# Note:

# Recall how to get index of maximum element

birds=np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock']  )
birds


array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw',
       'parrot', 'macaw', 'peacock'], dtype='<U7')

In [40]:
ages= np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])


In [41]:
ages


array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])

In [42]:
c=np.argmax(ages)
c


np.int64(7)

In [43]:
birds[c]


np.str_('parrot')

In [44]:
# You are a Teaching Assistant of the DSML course. You have access to every student’s marks in every quiz. The marks are stored in a matrix where matrix[i][j] represents the marks of the ith student in the jth quiz.

# The course instructor wants you to sort the marks of students according to jth quiz in increasing order so that he can evaluate the performance of students in that particular quiz.

# Here, you have to create a python program using which the instructor can sort the data on the basis of a given column(quiz). The program will return the matrix with the marks sorted in jth quiz.

# The dimension of the input matrix is m× n, the output is expected to be a 2d numpy matrix of dimension mxn, but in the output the jth column must be arranged in the ascending order.

# Note: The input will be 2D list not array. First convert it to array.

# Input Format:

# Number of test cases
# For each test case, number of rows for matrix and the column to be sorted in a new line.
# For each row in matrix, space separated integers are taken as input in a new line.
# Output Format:

# The 2D matrix, or each row in matrix space separated integers
# Sample Input:

#ToDO

# 1
# 3 2 
# 5 3 9
# 2 1 4
# 7 6 8
# Sample Output:

# [[2 1 4]
#  [5 3 9]
#  [7 6 8]]
# Explanation:

# The 2nd column of the matrix is [3, 1, 6], the column after sorting becomes [1, 3, 6].

# Note: While sorting the marks, take care of rearranging the relative order of rows too. As, [2 1 4] is a row at index 1 in the original matrix,
#  but after sorting the 2nd column, we had to rearrange its order as mentioned in the sample output.


In [ ]:
# Given a NumPy array, return the index of the first element that is greater than the target passed as an argument.

# Return -1, if there isn't any element greater than the target.

# Input Format:

# First line will have a list which is later typecasted to NumPy array
# Second line will have an integer representing target
# Output Format:

# A NumPy array consisting of one index
# Sample Input:

# arr = [-1,2,3,-4,5]
# target = 3
# Sample Output:

# [4]
# Sample Explanation:

# The first element greater than 3 in the array is 5 present at index 4, therefore a NumPy array of integer 4 is returned.


# Note: You are not expected to use any loop.

arr=np.array([-1,2,3,-4,5,6])
target=3
indx=np.argmax(arr>target)
indx
# arr=arr[indx]
# arg max normally gives the highest value indx , when passed with a condition it gives the first occurrance value


np.int64(4)