In [1]:
print("Welcome to Numpy-4")

Welcome to Numpy-4


## Agenda
  

- **Universal Functions (ufunc) on 2D**
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`✅
    
    - Axis argument ✅

    - Logical Operations✅
    
    - Sorting function - `sort()`, `argsort()`✅

             
- **Use Case: Fitness Data analysis**✅
    - Loading data set and EDA using numpy✅
    - `np.argmax()`✅

- **3D arrays**✅


- **Matrix Multiplication**
    - `matmul()`, `@`, `dot()`


- **Vectorization**
    - `np.vectorize()`    

- **Use Case: Image Manipulation using Numpy**
    - Opening an Image
    - Details of an image
    - Visualizing Channels
    - Rotating an Image (Transposing a Numpy Array)







In [3]:
import numpy as np
a=np.arange(100).reshape((10,10))

In [4]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a[][]

In [ ]:
a[ , ]

In [5]:
# Logical Operations

In [6]:
a= np.array([1,10,5,9])
b= np.array([12,13,43,5])

In [8]:
a

array([ 1, 10,  5,  9])

In [9]:
b

array([12, 13, 43,  5])

In [10]:
a<b


array([ True,  True,  True, False])

In [11]:
c= np.array([12,13,43,5,6])
c

array([12, 13, 43,  5,  6])

In [12]:
a<c

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [13]:
a<b

array([ True,  True,  True, False])

In [14]:
np.any(a<b)

True

In [15]:
a

array([ 1, 10,  5,  9])

In [28]:
d= np.array([12,13,43,10])
d

array([12, 13, 43, 10])

In [17]:
d<a

array([False, False, False, False])

In [18]:
np.any(d<a)

False

In [20]:
e= np.array([12,13,43,6])
e

array([12, 13, 43,  6])

In [23]:
a

array([ 1, 10,  5,  9])

In [25]:
e<a

array([False, False, False,  True])

In [26]:
np.any(e<a)

True

In [27]:
np.all(e<a)

False

In [30]:
a<d

array([ True,  True,  True,  True])

In [31]:
np.all(a<d)

True

In [34]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [35]:
(a<=b)

array([ True,  True,  True,  True])

In [36]:
(b<=c)

array([ True,  True,  True,  True])

In [37]:
np.all((a<=b) & (b<=c) )

True

In [ ]:
np.all(a<=b) & np.all(b<=c)

In [38]:
np.all(a<=b)

True

In [39]:
np.all(b<=c)

True

In [40]:
np.all(a<=b) & np.all(b<=c)

True

In [41]:
a=np.array([10,9,5,11,3,6,1])
a

array([10,  9,  5, 11,  3,  6,  1])

In [42]:
np.sort(a)

array([ 1,  3,  5,  6,  9, 10, 11])

In [48]:
np.argsort(a)

array([6, 4, 2, 5, 1, 0, 3])

In [43]:
np.max(a)

11

In [45]:
a

array([10,  9,  5, 11,  3,  6,  1])

In [44]:
np.argmax(a)

3

In [47]:
np.argmin(a)

6

In [49]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/Dec22_Adv_Dec22_Inter/Numpy_4/fit.txt
100%|██████████████████████████████████████| 3.43k/3.43k [00:00<00:00, 4.90MB/s]


In [50]:
data=np.loadtxt("/Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/Dec22_Adv_Dec22_Inter/Numpy_4/fit.txt",dtype="str")
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [51]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [52]:
data.shape

(96, 6)

In [55]:
date1=data[:,0]
date1

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [57]:
np.array([[1],[2],[3],[4]])

array([[1],
       [2],
       [3],
       [4]])

In [58]:
a,b,c,d=np.array([[1],[2],[3],[4]])

In [59]:
a

array([1])

In [63]:
# a,b,c,d=np.array([[1],[2],[3],[4]])

In [64]:
date,step_counts,mood,calories_burned,hours_sleep,activity= data.T

In [65]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [66]:
step_counts

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [67]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
# date = data[:,0]
# step_counts= data[:,1]
# mood= data[:,2]
# calories_burned= data[:,3]
# hours_sleep= data[:,4]
# activity= data[:,5]

In [68]:
step_counts=np.array(step_counts,dtype='int')
step_counts

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [69]:
calories_burned=np.array(calories_burned,dtype='int')
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [70]:
hours_sleep=np.array(hours_sleep,dtype='int')
hours_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [71]:
hours_sleep.dtype

dtype('int64')

In [72]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [74]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [75]:
np.mean(step_counts)

2935.9375

In [76]:
np.max(step_counts)

7422

In [77]:
np.argmax(step_counts)

69

In [78]:
date[np.argmax(step_counts)]

'14-12-2017'

In [79]:
calories_burned[np.argmin(step_counts)]

0

In [80]:
calories_burned[np.argmax(step_counts)]

243

In [81]:
mood[np.argmax(step_counts)]

'Happy'

In [83]:
mood=="Sad"

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
        True,  True, False, False, False, False])

In [86]:
step_counts[mood=="Sad"]

array([6041,   25, 5461, 4545, 4340, 1230,   61, 1258, 3148, 4687, 3519,
       1580, 2822,  181, 6676, 3721, 1648,  799, 1696,  221, 4061,  651,
        753,  518,  177,   36,  299,  702,  133])

In [88]:
step_counts[mood=="Sad"].mean()

2103.0689655172414

In [89]:
np.mean(step_counts[mood=="Sad"])

2103.0689655172414

In [90]:
np.mean(step_counts[mood=="Neutral"])

3153.777777777778

In [92]:
np.mean(step_counts[mood=="Happy"])

3392.725

In [93]:
step_counts>4000

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [94]:
mood[step_counts>4000]

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Neutral', 'Sad',
       'Happy', 'Neutral', 'Happy'], dtype='<U10')

In [95]:
np.unique(mood[step_counts>4000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [96]:
np.unique(mood[step_counts<2000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

In [97]:
np.unique(mood[step_counts<1000],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([10,  5, 13]))

In [101]:
hours_sleep.min()

2

In [102]:
hours_sleep.max()

9

In [103]:
hours_sleep.mean()

5.21875

In [105]:
result=np.unique(mood[hours_sleep<5],return_counts=True)
result

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([ 7,  9, 10]))

In [107]:
result[0][0]

'Happy'

In [108]:
result[1][0]

7

In [109]:
np.unique(mood[hours_sleep>7],return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([7, 1, 3]))

In [110]:
#3D array

In [112]:
r=np.arange(24).reshape((2,3,4))
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [113]:
len(r)

2

In [114]:
r.shape

(2, 3, 4)

In [115]:
r.size

24

In [116]:
a=np.array([2,7,1,9,3,5,15,10])
a

array([ 2,  7,  1,  9,  3,  5, 15, 10])

In [117]:
np.sort(a)

array([ 1,  2,  3,  5,  7,  9, 10, 15])

In [118]:
np.sort(a,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [119]:
np.sort(a,axis=0)

array([ 1,  2,  3,  5,  7,  9, 10, 15])

In [120]:
a

array([ 2,  7,  1,  9,  3,  5, 15, 10])

In [121]:
r=np.arange(24).reshape((3,4,2))
r

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [122]:
a=np.array([[[ 100,  15],[ 25,  36],[ 1,  51],[ 62,  77]],[[ 81,  9],[101, 11],[12, 130],[144, 155]],[[196, 17],[8, 19],[2, 21],[225, 23]]])
a

array([[[100,  15],
        [ 25,  36],
        [  1,  51],
        [ 62,  77]],

       [[ 81,   9],
        [101,  11],
        [ 12, 130],
        [144, 155]],

       [[196,  17],
        [  8,  19],
        [  2,  21],
        [225,  23]]])

In [123]:
a.shape

(3, 4, 2)

In [124]:
np.sort(a,axis=0)

array([[[ 81,   9],
        [  8,  11],
        [  1,  21],
        [ 62,  23]],

       [[100,  15],
        [ 25,  19],
        [  2,  51],
        [144,  77]],

       [[196,  17],
        [101,  36],
        [ 12, 130],
        [225, 155]]])

In [125]:
np.sort(a,axis=1)

array([[[  1,  15],
        [ 25,  36],
        [ 62,  51],
        [100,  77]],

       [[ 12,   9],
        [ 81,  11],
        [101, 130],
        [144, 155]],

       [[  2,  17],
        [  8,  19],
        [196,  21],
        [225,  23]]])

In [126]:
np.sort(a,axis=2)

array([[[ 15, 100],
        [ 25,  36],
        [  1,  51],
        [ 62,  77]],

       [[  9,  81],
        [ 11, 101],
        [ 12, 130],
        [144, 155]],

       [[ 17, 196],
        [  8,  19],
        [  2,  21],
        [ 23, 225]]])

In [127]:
np.sort(a,axis=-1)

array([[[ 15, 100],
        [ 25,  36],
        [  1,  51],
        [ 62,  77]],

       [[  9,  81],
        [ 11, 101],
        [ 12, 130],
        [144, 155]],

       [[ 17, 196],
        [  8,  19],
        [  2,  21],
        [ 23, 225]]])

In [137]:
np.sort(a,axis=-2)

array([[[  1,  15],
        [ 25,  36],
        [ 62,  51],
        [100,  77]],

       [[ 12,   9],
        [ 81,  11],
        [101, 130],
        [144, 155]],

       [[  2,  17],
        [  8,  19],
        [196,  21],
        [225,  23]]])

In [129]:
np.sort(a,axis=-3)

array([[[ 81,   9],
        [  8,  11],
        [  1,  21],
        [ 62,  23]],

       [[100,  15],
        [ 25,  19],
        [  2,  51],
        [144,  77]],

       [[196,  17],
        [101,  36],
        [ 12, 130],
        [225, 155]]])

In [136]:
np.sort(a.flatten()).reshape((3,4,2))

array([[[  1,   2],
        [  8,   9],
        [ 11,  12],
        [ 15,  17]],

       [[ 19,  21],
        [ 23,  25],
        [ 36,  51],
        [ 62,  77]],

       [[ 81, 100],
        [101, 130],
        [144, 155],
        [196, 225]]])